
image: gitpod/workspace-python-3.12

# Commands that will run on workspace start
# tasks:
#     - name: Setup, Install & Build
#       before: yarn global add express
#       init: yarn install
#       command: yarn build

# Ports to expose on workspace startup
# ports:
#     - port: 3000
#       onOpen: open-preview
#       name: Website
#       description: Website Preview

vscode:
  extensions:
    - ms-python.python
    - sumneko.lua
    - cschleiden.vscode-github-actions
    - JackMacWindows.vscode-computercraft
