[project]
name = "Helium"
version = "0.0.1"
authors = [
  { name="TheKidThatCodes" },
]
description = "Helium Sol VM"
readme = "README.md"
requires-python = "~3.12"

[tool.autopep8]
max_line_length = 1200
# in-place = true
# recursive = true
aggressive = 3